### ISSUE TITLE
SelectElement is missing in this

### ISSUE THREAD

**Issue by Testirovishik** [DotNetSeleniumTools/DotNetSeleniumExtras#1]
When using this new library instead of the Selenium Support to use migrated ExpectedConditions, the SelectElement is missing in this library. I can use both libraries for now, but it is forcing me to work around by explicitly declaring which ExpectedCondition to use. Is there a plan to include SelectElement as well?

**Comment by algot** [comment]
The same issue if I use WebDriverWait and ExpectedConditions at the same time

`using OpenQA.Selenium.Support.UI;`
`using ExpectedConditions = SeleniumExtras.WaitHelpers.ExpectedConditions;`
`internal static class Class1`
`{`
`      var wait = new WebDriverWait(WebDriverManager.Driver, TimeSpan.FromSeconds(5));`
`      wait.Until(ExpectedConditions.FrameToBeAvailableAndSwitchToIt(iframeId));`
`}`

**Comment by jimevans** [comment]
This repository accepts neither issue reports nor pull requests until a new owner for it steps forward. Eventually, the `ExpectedConditions` implementation in the Selenium project will be removed, which would resolve the issue as well. In the meantime, you’ll need to be explicit about the namespace.
