### ISSUE TITLE
PageFactory type missing on netstandard2.0

### ISSUE THREAD

**Issue by macpak** [DotNetSeleniumTools/DotNetSeleniumExtras#4]
Hi ,

I've noticed that the PageFactory type is not supported/invisible on netstandard2.0. Are you planning to add the support ?

**Comment by jimevans** [comment]
You’ll have to take that up with the new maintainer of this repository, once someone is located who is willing and able to volunteer to do so. Until that time, the answer is no, no changes whatsoever are planned to this library.
