### ISSUE TITLE
Interesting in taking ownership of this project...

### ISSUE THREAD

**Issue by joltcoder** [DotNetSeleniumTools/DotNetSeleniumExtras#6]
If possible, I'd like to chat a bit about it... please let me know if there is a preferred way of doing this.

**Comment by jimevans** [comment]
@joltcoder This is not really an issue, so I'm going to close it. I can be contacted via email, on Twitter (@jimevansmusic), or in the Selenium project's IRC channel (#selenium on Freenode, but also [mirrored via Slack](https://seleniumhq.herokuapp.com)).
